### PR TITLE
Add comment to ignore golint error 

### PR DESCRIPTION
**Pull request by soniasingla**
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>

### CODE REVIEW

**Comment by natalieparellano** [comment]
Since we're not actually trying to produce HTML here I wonder if it's better to just ignore the warning.

**Comment by soniasingla** [comment]
> Since we're not actually trying to produce HTML here I wonder if it's better to just ignore the warning.

Should I add ``// ignore`` comment? @natalieparellano

**Comment by natalieparellano** [comment]
Apologies for the slow reply! I think for now that is the best option.

**Review by natalieparellano — APPROVED** [review]

**Comment by natalieparellano** [comment]
I was trying to see if there's a more granular way to suppress the warning (like `// #nosec G204`), but for now I don't think so.

**Review by yaelharel — APPROVED** [review]

**Pull request merged**
